name: Checks

on: [push, pull_request]

jobs:
  reflection:
    name: Reflection checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: mvn-${{ hashFiles('project.clj') }}
        restore-keys: |
          mvn-

    - name: Install dependencies
      run: |
        set -euo pipefail
        lein with-profile +clj-kondo,+kaocha deps

    - name: Run reflection check
      run: |
        set -euo pipefail
        lein check 2>&1 | tee check.out
        ! grep 'Reflection warning, tortilla/' check.out

  lint:
    name: Linter checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: mvn-${{ hashFiles('project.clj') }}
        restore-keys: |
          mvn-

    - name: Install dependencies
      run: |
        set -euo pipefail
        lein with-profile +clj-kondo,+kaocha deps

    - name: Run lint check
      run: |
        set -euo pipefail
        lein lint

  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: mvn-${{ hashFiles('project.clj') }}
        restore-keys: |
          mvn-

    - name: Install dependencies
      run: |
        set -euo pipefail
        lein with-profile +clj-kondo,+kaocha deps

    - name: Run tests
      run: |
        set -euo pipefail
        bin/kaocha

    - name: Push coverage to Coveralls.io
      run: |
        set -euo pipefail
        bin/fixup_paths.sh
        PR=$(bin/github_pr.sh ${{github.event_name}} ${{github.ref}})
        bin/coveralls.sh --token ${{secrets.CoverallsToken}} --pull "$PR"

  binary:
    name: CLI binary checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: mvn-${{ hashFiles('project.clj') }}
        restore-keys: |
          mvn-

    - name: Install dependencies
      run: |
        set -euo pipefail
        lein with-profile +clj-kondo,+kaocha deps

    - name: Build CLI binary
      run: |
        set -euo pipefail
        lein bin

    - name: Run CLI and write generated code
      run: |
        set -euo pipefail
        ./bin/tortilla -w 150 -c tortilla.testing.TestClass -n tortilla.test-class -o src/gen/tortilla/test_class.clj

    - name: Run CLI on a dynamically loaded dependency
      run: |
        set -euo pipefail
        ./bin/tortilla -d net.minidev:json-smart:2.3 -c net.minidev.json.JSONObject -m

    - name: Run reflection check on generated code
      run: |
        set -euo pipefail
        lein with-profile +gen check 2>&1 | tee check-gen.out
        ! grep 'Reflection warning, tortilla/' check-gen.out

    - name: Run lint check on generated code
      run: |
        set -euo pipefail
        lein clj-kondo --lint src/gen
